name: Build Container Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ut2004-dedicated-server
          tags: 3369.3-dev ${{ github.sha }}
          containerfiles: |
            ./Containerfile
